version: "3.8"

services:
    store:
        image: "redis:latest"
        container_name: child-process-store
        ports:
            - "6379:6379"
        volumes: 
            - cache:/data
        

    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: child-process-app
        ports:
            - "8080:8080"
        environment:
            REDIS_HOST: store
            REDIS_PORT: 6379
            PORT: 8080
        depends_on:
            - store
volumes:
  cache:
    driver: local
